### ISSUE TITLE
The V3 plugins

### ISSUE THREAD

**Issue by gsioteam** [gsioteam/env#3]
This thread list plugins for [Kinoko](https://github.com/gsioteam/kinoko). If there are new plugins you want to appear in the plugin list, you can open a comment and write the following information about the plugin. 

```yaml
# Signature token. Leave this attribute blank. I will calculate out this token.
token: 4uuH8_OZtJLKiPCYktAKkLqmS36RDdxB_7a74QaszcysGA9Xp1_Y3jBQ2Espl_GoU_RxTc5MzXAEGJpe_igdnA
# Required. The title of this plugin, will be display in the plguin list
title: ninemanga(EN,ES,RU,DE,IT,PT,FR)
# Optional. The icon of this plugin, will be display in the plguin list
icon: https://raw.githubusercontent.com/gsioteam/ninemanga/v3/icon.png
# Required. The git url to clone this plugin scripts.
src: https://github.com/gsioteam/ninemanga.git
# Optional. The branch of the git repository. (default: master)
branch: v3
# Optional. Will not appear in the plugin list if ignore is true.
ignore: true
```
